name = "premise-selection"
testDriver = "PremiseSelectionTest"
defaultTargets = ["PremiseSelection"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.18.0"

[[lean_lib]]
name = "PremiseSelection"

[[lean_lib]]
name = "PremiseSelectionTest"
